/*
 * AppletRestaUm.java
 *
 * Created on 18 de Outubro de 2008, 15:24
 */

package br.ufrn.dca.restaum.gui;

import javax.swing.SwingUtilities;

/**
 *
 * @author  Alexandre
 */
public class AppletRestaUm extends javax.swing.JApplet {
    
    /** Initializes the applet AppletRestaUm */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRestaUmDinamico1 = new PnlRestaUmDinamico(6);
        jMenuBar1 = new javax.swing.JMenuBar();
        mnJogo = new javax.swing.JMenu();
        mntNovoJogo = new javax.swing.JMenuItem();
        mntConfiguracoes = new javax.swing.JMenuItem();
        mntPilotoAutomatico = new javax.swing.JMenuItem();

        mnJogo.setText("Jogo");

        mntNovoJogo.setText("Novo Jogo");
        mntNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntNovoJogoActionPerformed(evt);
            }
        });
        mnJogo.add(mntNovoJogo);

        mntConfiguracoes.setText("Configurações");
        mntConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntConfiguracoesActionPerformed(evt);
            }
        });
        mnJogo.add(mntConfiguracoes);

        mntPilotoAutomatico.setText("Piloto Automático");
        mntPilotoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntPilotoAutomaticoActionPerformed(evt);
            }
        });
        mnJogo.add(mntPilotoAutomatico);

        jMenuBar1.add(mnJogo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRestaUmDinamico1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRestaUmDinamico1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mntNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntNovoJogoActionPerformed
        pnlRestaUmDinamico1.novoJogo();
}//GEN-LAST:event_mntNovoJogoActionPerformed

    private void mntConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntConfiguracoesActionPerformed
        FrmConfiguracoes frm = new FrmConfiguracoes(null, pnlRestaUmDinamico1);
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
    }//GEN-LAST:event_mntConfiguracoesActionPerformed

    private void mntPilotoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntPilotoAutomaticoActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                pnlRestaUmDinamico1.jogarAutomaticamente();
            }
        });
    }//GEN-LAST:event_mntPilotoAutomaticoActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnJogo;
    private javax.swing.JMenuItem mntConfiguracoes;
    private javax.swing.JMenuItem mntNovoJogo;
    private javax.swing.JMenuItem mntPilotoAutomatico;
    private br.ufrn.dca.restaum.gui.PnlRestaUmDinamico pnlRestaUmDinamico1;
    // End of variables declaration//GEN-END:variables
    
}
