/*
 * FrmConfiguracoes.java
 *
 * Created on 27 de Outubro de 2008, 23:07
 */

package br.ufrn.dca.restaum.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author  Alexandre
 */
public class FrmConfiguracoes extends javax.swing.JDialog {
    
    private PnlRestaUmDinamico pnlRestaUm;
    
    /** Creates new form FrmConfiguracoes */
    public FrmConfiguracoes(java.awt.Frame parent, PnlRestaUmDinamico pnl) {
        super(parent, true);
        initComponents();
        this.pnlRestaUm = pnl;
        txtQtdInicial.setText(String.valueOf(pnlRestaUm.getTabuleiro().getQtdIncialCasasVazias()));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtQtdInicial = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTempoPiloto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações");

        jLabel1.setText("Quantidade inicial de casas vazias");

        txtQtdInicial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQtdInicial.setName("QUANTIDADE INICIAL"); // NOI18N

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tempo do piloto automático (ms)");

        txtTempoPiloto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTempoPiloto.setName("TEMPO"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(txtTempoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQtdInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int qtd = Integer.parseInt(txtQtdInicial.getText());
            pnlRestaUm.getTabuleiro().setQuantidadeInicialDeCasasVazias(qtd);
            qtd = Integer.parseInt(txtTempoPiloto.getText());
            pnlRestaUm.setTimeStep(qtd);
            dispose();
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Valor inválido para o campo", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
            txtQtdInicial.requestFocusInWindow();
            txtQtdInicial.selectAll();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtQtdInicial;
    private javax.swing.JTextField txtTempoPiloto;
    // End of variables declaration//GEN-END:variables
    
}
