/*
 * FrmRestaUm.java
 *
 * Created on 15 de Outubro de 2008, 20:25
 */

package br.ufrn.dca.restaum.gui;

import java.awt.BorderLayout;

/**
 *
 * @author  Alexandre
 */
public class FrmRestaUm extends javax.swing.JFrame {
    
    /** Creates new form FrmRestaUm */
    public FrmRestaUm() {
        initComponents();
        /*PnlRestaUm pnl = new PnlRestaUm();
        getContentPane().add(pnl, BorderLayout.CENTER);*/
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRestaUmDinamico1 = new br.ufrn.dca.restaum.gui.PnlRestaUmDinamico();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(pnlRestaUmDinamico1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRestaUm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.ufrn.dca.restaum.gui.PnlRestaUmDinamico pnlRestaUmDinamico1;
    // End of variables declaration//GEN-END:variables
    
}
